modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (24 is current forge version)
credits="Thanks to Harry Talks for his amazing tutorials." #optional
authors="Harry" #optional

[[mods]] #mandatory
modId="techcraft" #mandatory
version="0.1" #mandatory
displayName="Harry's Tutorial Mod" #mandatory
description='''
This is my mod.
It's great.
Sub 2 pewdiepie
'''

[[dependencies.tutorialmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[26,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"